### ISSUE TITLE
Android: Clustering only render for at least 5>= annotation and not for less than 5.

### ISSUE THREAD

**Issue by reactnative103** [tidev/ti.map#267]
Hi,

I am using latest ti.map module version 4.3.0. 

if we have 3 or 4 annotation on near by place to each other, clustering not showing for this. 
While If I increase the annotation count to 5 or more, clustering is showing in android.

iOS working fine but not android.

Can you please help me out for the same.

Thanks & Regards,
Hemant Solanki

**Comment by m1ga** [comment]
Hi @Hemantsolanki103 
I've created a PR #269 with this feature!
You can test it with [this module](http://migaweb.de/ti.map-android-4.4.1.zip)

**Comment by Hemantsolanki103** [comment]
Hi Michael,

Thanks for your great help. I am really grateful to you.

Thanks & Regards,
Hemant Solanki
